language: python
env:
  - APP=redundancy_payments_alpha
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r $APP/requirements.dev.txt --use-mirrors
# command to run tests
script:
  - cd $APP; nosetests --exe -a '!integration'
notifications:
  email: false
