language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install -r redundancy_payments_alpha/requirements.dev.txt --use-mirrors
# command to run tests
script:
  - cd redundancy_payments_alpha; ./run_tests.sh
notifications:
  email: false
