#!/usr/bin/env python
import argparse

from insolvency_practitioner_forms import routes

def run(args):
    if args.debug:
        routes.app.debug = True
    routes.app.run(host='0.0.0.0', port=8001, threaded=True)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Run the insolvency practitioner web app")
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()
    run(args)
