#!/usr/bin/env python

from birmingham_cabinet.api import add_rp14a_form
from json import loads
import os

employee = {
        "employer_name": "Ironcore Mining Ltd.",
        "employee_title": "Mr",
        "employee_forenames": "Barry",
        "employee_surname": "McSteve",
        "employee_national_insurance_number": "MB999999C",
        "employee_date_of_birth": "06/21/1969",
        "employee_basic_weekly_pay": "475",
        "employee_owed_wages_in_arrears": "950",
        "employee_holiday_owed": "10"
    }
 
def store_data():
    add_rp14a_form(employee)


if __name__ == "__main__":
    store_data()

