#!/usr/bin/env python

from birmingham_cabinet.api import add_rp14a_form
from json import loads
import os


def store_data(path_to_file):
    with open(path_to_file) as f:
        records = loads(f.read())
        for form in records:
            add_rp14a_form(form)


if __name__ == "__main__":
    path_to_file = os.path.join(os.path.dirname(__file__), 'user_research_data.json')
    store_data(path_to_file)

